### PR TITLE
Add support for LiveEEx

### PR DESCRIPTION
**Pull request by dnsbty**
When Phoenix LiveView was released, it brought with it the concept of a LiveEEx file. I'm hoping you will agree that we should be adding support for it here. If not, I'm happy to make a separate package for it.

### CODE REVIEW

**Comment by keathley** [comment]
This looks good to me. Did liveEEx add any new syntax bits? or was it just the file extension?

**Comment by dnsbty** [comment]
As far as I've seen so far, it just adds new attributes to HTML elements. That might change as the project matures more though.

**Comment by keathley** [comment]
I see. If we need to adapt the syntax in the future we can do that then. Otherwise this looks good to me :+1:

**Comment by keathley** [comment]
I can push a new release out soon that will include this addition. Thanks @dnsbty!

**Comment by dnsbty** [comment]
Awesome! Thanks for maintaining, Chris!

**Comment by kiere** [comment]
@keathley Any idea when this might make it into production?  `v0.22.1` is still showing as the latest release for me in Atom.

**Comment by keathley** [comment]
@kiere Yup. sorry about that. This fell through the cracks.

**Comment by keathley** [comment]
@kiere so sorry again about the delay. A new version has been published.

**Comment by kiere** [comment]
@keathley Got it!!

**Pull request merged**
